type Flag = typeof FlagNames[number];

export const FlagNames = [
	"CORE_LOG_LEVEL_FILE",
	"CORE_LOG_LEVEL",
	"CORE_MAX_TRANSACTIONS_IN_POOL",
	"CORE_NETWORK_NAME",
	"CORE_P2P_HOST",
	"CORE_P2P_MAX_PEERS_SAME_SUBNET",
	"CORE_P2P_MIN_NETWORK_REACH",
	"CORE_P2P_PORT",
	"CORE_P2P_PORT",
	"CORE_P2P_RATE_LIMIT_POST_TRANSACTIONS",
	"CORE_P2P_RATE_LIMIT",
	"CORE_PATH_DATA",
	"CORE_TRANSACTION_POOL_DISABLED",
	"CORE_TRANSACTION_POOL_MAX_PER_REQUEST",
	"CORE_TRANSACTION_POOL_MAX_PER_SENDER",
	"CORE_WALLET_SYNC_ENABLED",
	"CORE_WEBHOOKS_ENABLED",
	"CORE_WEBHOOKS_HOST",
	"CORE_WEBHOOKS_PORT",
	"CORE_WEBHOOKS_TIMEOUT",
] as const;

export const Flags = FlagNames.reduce((item, flagName) => {
	item[flagName] = flagName;
	return item;
}, {}) as Record<Flag, string>;
