name: Benchmarking

on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    types: [ready_for_review, synchronize, opened]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & Build
        run: yarn setup

      - name: Benchmark
        run: yarn bench
