name: Contributors

on:
    push:
        branches:
            - "main"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    readme:
        runs-on: ubuntu-latest

        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.3
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
