name: Unit Testing

on:
    push:
        branches:
            - "main"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    core:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core && pnpm run test

    core-api:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-api && pnpm run test

    core-blockchain:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-blockchain && pnpm run test

    core-cli:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-cli && pnpm run test

    core-database:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-database && pnpm run test

    core-forger:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-forger && pnpm run test

    core-kernel:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-kernel && pnpm run test

    core-logger-pino:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-logger-pino && pnpm run test

    core-p2p:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-p2p && pnpm run test

    core-snapshots:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-snapshots && pnpm run test

    core-state:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-state && pnpm run test

    core-test-framework:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-test-framework && pnpm run test

    core-transaction-pool:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-transaction-pool && pnpm run test

    core-transactions:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-transactions && pnpm run test

    core-webhooks:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-webhooks && pnpm run test

    crypto:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/crypto && pnpm run test

    core-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python 2.7
              uses: actions/setup-python@v2
              with:
                  python-version: "2.7"

            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: latest
                  run_install: true

            - name: Build
              run: pnpm run setup

            - name: Test
              run: cd packages/core-test && pnpm run test
