jobs:
    unit:
        concurrency:
            cancel-in-progress: true
            group: ${{ github.head_ref }}-unit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  run_install: true
                  version: latest
            - uses: actions/setup-node@v2
              with:
                  cache: pnpm
                  node-version: ${{ matrix.node-version }}
            - name: Build
              run: pnpm run build && cd packages
            - name: Test core
              run: cd core && pnpm run test && cd ..
            - name: Test core-api
              run: cd core-api && pnpm run test && cd ..
            - name: Test core-blockchain
              run: cd core-blockchain && pnpm run test && cd ..
            - name: Test core-cli
              run: cd core-cli && pnpm run test && cd ..
            - name: Test core-crypto-address-base58
              run: cd core-crypto-address-base58 && pnpm run test && cd ..
            - name: Test core-crypto-address-bech32
              run: cd core-crypto-address-bech32 && pnpm run test && cd ..
            - name: Test core-crypto-address-bech32m
              run: cd core-crypto-address-bech32m && pnpm run test && cd ..
            - name: Test core-crypto-address-keccak256
              run: cd core-crypto-address-keccak256 && pnpm run test && cd ..
            - name: Test core-crypto-address-ss58
              run: cd core-crypto-address-ss58 && pnpm run test && cd ..
            - name: Test core-crypto-hash-bcrypto
              run: cd core-crypto-hash-bcrypto && pnpm run test && cd ..
            - name: Test core-crypto-hash-noble
              run: cd core-crypto-hash-noble && pnpm run test && cd ..
            - name: Test core-crypto-hash-wasm
              run: cd core-crypto-hash-wasm && pnpm run test && cd ..
            - name: Test core-crypto-key-pair-bls12-381
              run: cd core-crypto-key-pair-bls12-381 && pnpm run test && cd ..
            - name: Test core-crypto-key-pair-ecdsa
              run: cd core-crypto-key-pair-ecdsa && pnpm run test && cd ..
            - name: Test core-crypto-key-pair-ed25519
              run: cd core-crypto-key-pair-ed25519 && pnpm run test && cd ..
            - name: Test core-crypto-key-pair-schnorr
              run: cd core-crypto-key-pair-schnorr && pnpm run test && cd ..
            - name: Test core-crypto-signature-bls12-381
              run: cd core-crypto-signature-bls12-381 && pnpm run test && cd ..
            - name: Test core-crypto-signature-ecdsa
              run: cd core-crypto-signature-ecdsa && pnpm run test && cd ..
            - name: Test core-crypto-signature-ed25519
              run: cd core-crypto-signature-ed25519 && pnpm run test && cd ..
            - name: Test core-crypto-signature-schnorr
              run: cd core-crypto-signature-schnorr && pnpm run test && cd ..
            - name: Test core-database
              run: cd core-database && pnpm run test && cd ..
            - name: Test core-forger
              run: cd core-forger && pnpm run test && cd ..
            - name: Test core-kernel
              run: cd core-kernel && pnpm run test && cd ..
            - name: Test core-logger-pino
              run: cd core-logger-pino && pnpm run test && cd ..
            - name: Test core-p2p
              run: cd core-p2p && pnpm run test && cd ..
            - name: Test core-state
              run: cd core-state && pnpm run test && cd ..
            - name: Test core-test-framework
              run: cd core-test-framework && pnpm run test && cd ..
            - name: Test core-transaction-pool
              run: cd core-transaction-pool && pnpm run test && cd ..
            - name: Test core-transactions
              run: cd core-transactions && pnpm run test && cd ..
            - name: Test core-webhooks
              run: cd core-webhooks && pnpm run test && cd ..
            - name: Test crypto
              run: cd crypto && pnpm run test && cd ..
            - name: Test utils
              run: cd utils && pnpm run test && cd ..
        strategy:
            matrix:
                node-version:
                    - 16.x
name: Unit
on:
    pull_request:
        types:
            - ready_for_review
            - synchronize
            - opened
    push:
        branches:
            - main
            - develop
